shop/Models/Order.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using OnlineShopWebApp.Models.Enums;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.Contracts;

namespace OnlineShopWebApp.Models
{
    public class Order
    {
        private static int _idCounter = 1;

        public int Id { get; set; }

        [Required(ErrorMessage = "Введите имя")]
        public required string Name {  get; set; }

        [Required(ErrorMessage = "Укажите адрес доставки")]
        public required string Address { get; set; }

        [Required(ErrorMessage = "Укажите ваш email")]
        [EmailAddress(ErrorMessage = "Введите валидный email")]
        public required string Email { get; set; }

        [Required(ErrorMessage = "Введите телефон для связи")]
        [Phone(ErrorMessage = "Введите номер в формате +7 123 456 78 90")]
        public required string Phone { get; set; }

        public CartViewModel? Cart { get; set; }

        public OrderStatuses Status { get; set; }

        public DateTime Date { get; set; }

        public Order()
        {
            Id = _idCounter;
            Date = DateTime.Now;
            Status = OrderStatuses.Created;

            _idCounter++;
        }
    }
}

shop/Models/OrderViewModel.cs
using OnlineShop.Dbp.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace OnlineShopWebApp.Models
{
    public class OrderViewModel
    {
        public Guid Id { get; set; }
        [Required(ErrorMessage = "Введите имя")]
        public required string Name {  get; set; }
        [Required(ErrorMessage = "Укажите адрес доставки")]
        public required string Address { get; set; }
        [Required(ErrorMessage = "Укажите ваш email")]
        [EmailAddress(ErrorMessage = "Введите валидный email")]
        public required string Email { get; set; }
        [Required(ErrorMessage = "Введите телефон для связи")]
        [Phone(ErrorMessage = "Введите номер в формате +7 123 456 78 90")]
        public required string Phone { get; set; }
        public OrderStatuses Status { get; set; } = OrderStatuses.Created;
        public DateTime Date { get; set; } = DateTime.Now;
        public decimal Cost => Items.Sum(item =>  item.Cost);
        public List<OrderItemViewModel> Items { get; set; } = [];
    }
}

shop/Models/ProductViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace OnlineShopWebApp.Models
{
    public class ProductViewModel
    {
        public Guid Id { get; set; }

        [Required(ErrorMessage = "Введите название продукта")]
        public required string Name { get; set; }

        [Required(ErrorMessage = "Введите цену продукта")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Цена не может быть отрицательной")]
        public decimal Price { get; set; }

        [Required(ErrorMessage = "Добавьте описание продукта")]
        public required string Description { get; set; }

        [Required(ErrorMessage = "Добавьте ссылку на фото продукта")]
        public required string ImageUrl { get; set; }
    }
}

shop/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db.Services;
using OnlineShopWebApp.Models;
using OnlineShopWebApp.Properties.Helpers;
using OnlineShopWebApp.Services;

namespace OnlineShopWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly IProductsStorage _productsStorage;
        private readonly IOrdersStorage _ordersStorage;
        private readonly IRolesStorage _rolesStorage;
        private readonly IUsersStorage _usersStorage;

        public HomeController
        (
            IProductsStorage productsStorage,
            IOrdersStorage ordersStorage,
            IRolesStorage rolesStorage,
            IUsersStorage usersStorage
        )
        {
            _productsStorage = productsStorage;
            _ordersStorage = ordersStorage;
            _rolesStorage = rolesStorage;
            _usersStorage = usersStorage;
        }

        public IActionResult Orders()
        {
            var ordersDb = _ordersStorage.GetAll();
            var orders = ordersDb.ToOrderViewModel();

            return View(orders);
        }

        public IActionResult Users()
        {
            var users = _usersStorage.GetAll();

            return View(users);
        }

        public IActionResult Roles()
        {
            var roles = _rolesStorage.GetAll();

            return View(roles);
        }

        public IActionResult Products()
        {
            var productsDb = _productsStorage.GetAll();
            var products = new List<ProductViewModel>();

            foreach (var productDb in productsDb)
            {
                var product = new ProductViewModel
                {
                    Id = productDb.Id,
                    Name = productDb.Name,
                    Price = productDb.Price,
                    Description = productDb.Description,
                    ImageUrl = productDb.ImageUrl,
                };

                products.Add(product);
            }

            return View(products);
        }
    }
}

shop/Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db.Services;
using OnlineShop.Dbp.Models.Enums;
using OnlineShopWebApp.Properties.Helpers;

namespace OnlineShopWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OrderController : Controller
    {
        private readonly IOrdersStorage _ordersStorage;

        public OrderController(IOrdersStorage ordersStorage)
        {
            _ordersStorage = ordersStorage;
        }

        [HttpGet]
        public IActionResult Details(Guid id)
        {
            var order = _ordersStorage.TryGetById(id);

            return View(order?.ToOrderViewModel());
        }

        [HttpPost]
        public IActionResult Details(Guid id, OrderStatuses status)
        {
            var order = _ordersStorage.TryGetById(id);

            if (order != null)
            {
                _ordersStorage.ChangeStatus(id, status);
                order.Status = status;
            }

            return View(order?.ToOrderViewModel());
        }
    }
}

shop/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db.Models;
using OnlineShop.Db.Services;
using OnlineShopWebApp.Models;
using OnlineShopWebApp.Properties.Helpers;

namespace OnlineShopWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IProductsStorage _productsStorage;

        public ProductController(IProductsStorage productsStorage)
        {
            _productsStorage = productsStorage;
        }

        public IActionResult Details(Guid id)
        {
            var productDb = _productsStorage.TryGetById(id);

            if (productDb == null)
            {
                return RedirectToAction("Products", "Home");
            }

            var product = productDb.ToProductViewModel();

            return View(product);
        }

        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            var productDb = _productsStorage.TryGetById(id);

            if (productDb == null)
            {
                return RedirectToAction("Products", "Home");
            }

            var product = productDb.ToProductViewModel();

            return View(product);
        }

        [HttpPost]
        public IActionResult Edit(ProductViewModel product)
        {
            if (product.Price == 0)
            {
                ModelState["Price"]?.Errors.Clear();
                ModelState.AddModelError("Price", "Введите цену");
            }

            if (ModelState.IsValid == false)
            {
                return View(product);
            }

            var productDb = product.ToProduct();

            _productsStorage.Update(productDb);

            return RedirectToAction("Products", "Home");
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(ProductViewModel product)
        {
            if (product.Price == 0)
            {
                ModelState["Price"]?.Errors.Clear();
                ModelState.AddModelError("Price", "Введите цену");
            }

            if (ModelState.IsValid == false)
            {
                return View(product);
            }

            var productDb = product.ToProduct();

            _productsStorage.Add(productDb);

            return RedirectToAction("Products", "Home");
        }

        public IActionResult Remove(Guid id)
        {
            var product = _productsStorage.TryGetById(id);

            if (product != null)
            {
                _productsStorage.Remove(product);
            }

            return RedirectToAction("Products", "Home");
        }
    }
}

shop/Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShopWebApp.Models;
using OnlineShopWebApp.Services;

namespace OnlineShopWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RoleController : Controller
    {
        private readonly IRolesStorage _rolesStorage;

        public RoleController(IRolesStorage rolesStorage)
        {
            _rolesStorage = rolesStorage;
        }

        public IActionResult Remove(string name)
        {
            var role = _rolesStorage.TryGetByName(name);

            if (role != null)
            {
                _rolesStorage.Remove(role);
            }

            return RedirectToAction("Roles", "Home");
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Role role)
        {
            var existing = _rolesStorage.TryGetByName(role.Name);

            if (existing != null)
            {
                ModelState.AddModelError("", "Такая роль уже существует");
            }

            if (ModelState.IsValid)
            {
                _rolesStorage.Add(role);

                return RedirectToAction("Roles", "Home");
            }

            return View(role);
        }
    }
}

shop/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShopWebApp.Models;
using OnlineShopWebApp.Services;

namespace OnlineShopWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly IUsersStorage _usersStorage;

        public UserController(IUsersStorage usersStorage) 
        {
            _usersStorage = usersStorage;
        }

        public IActionResult Details(Guid id)
        {
            var user = _usersStorage.GetById(id);

            if (user != null)
            {
                return View(user);
            }

            return RedirectToAction("Users", "Home");
        }

        [HttpGet]
        public IActionResult ChangePassword(Guid id)
        {
            var pass = new Pass() { Id = id };

            return View(pass);
        }

        [HttpPost]
        public IActionResult ChangePassword(Pass pass)
        {
            var user = _usersStorage.GetById(pass.Id);

            if (user == null)
            {
                return RedirectToAction("Users", "Home");
            }
            else if (user.Password != pass.OldPassword)
            {
                ModelState.AddModelError(nameof(pass.OldPassword), "Неверный пароль");
            }

            if (ModelState.IsValid == false)
            {
                return View(pass);
            }

            if (pass.NewPassword != null && pass.ConfirmNewPassword != null)
            {
                user.Password = pass.NewPassword;
                user.ConfirmPassword = pass.ConfirmNewPassword;
            }

            return RedirectToAction(nameof(Details), new { pass.Id });
        }

        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            var user = _usersStorage.GetById(id);

            if (user != null)
            {
                var userInfo = new UserInfo()
                {
                    Id = user.Id,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    Login = user.Login,
                    Email = user.Email,
                    Phone = user.Phone
                };

                return View(userInfo);
            }

            return RedirectToAction("Users", "Home");
        }

        [HttpPost]
        public IActionResult Edit(UserInfo userInfo)
        {
            if (ModelState.IsValid == false)
            {
                return View(userInfo);
            }

            var user = _usersStorage.GetById(userInfo.Id);

            if (user == null)
            {
                return RedirectToAction("Users", "Home");
            }

            user.FirstName = userInfo.FirstName;
            user.LastName = userInfo.LastName;
            user.Login = userInfo.Login;
            user.Email = userInfo.Email;
            user.Phone = userInfo.Phone;

            return RedirectToAction("Details", new { userInfo.Id });
        }

        public IActionResult Remove(Guid id)
        {
            var user = _usersStorage.GetById(id);

            if (user != null)
            {
                _usersStorage.Remove(user);
            }

            return RedirectToAction("Users", "Home");
        }
    }
}

shop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using shop.Models;
using System.Diagnostics;
using OnlineShopWebApp.Properties.Helpers;
using OnlineShopWebApp.Services;
using OnlineShop.Db.Services;

namespace shop.Controllers
{
    public class HomeController : Controller
    {
        private readonly IProductsStorage _productsStorage;
        private readonly IUsersStorage _usersStorage;

        public HomeController(IProductsStorage productsStorage, IUsersStorage usersStorage)
        {
            _productsStorage = productsStorage;
            _usersStorage = usersStorage;
        }

        public IActionResult Index(string? searchName)
        {
            var productsDb = _productsStorage.GetAll();
            var products = productsDb.ToProductViewModel();

            if (string.IsNullOrEmpty(searchName) == false || string.IsNullOrWhiteSpace(searchName) == false)
            {
                products = products
                    .Where(p => p.Name.ToLower().Contains(searchName.ToLower()))
                    .ToList();
            }

            ViewBag.UserId = _usersStorage.GetCurrentUserId();
            ViewBag.SearchName = searchName;
            return View(products);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

shop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db.Models;
using OnlineShop.Db.Services;
using OnlineShopWebApp.Models;

namespace OnlineShopWebApp.Controllers
{
    public class OrderController : Controller
    {
        private ICartsStorage _cartsStorage;
        private IOrdersStorage _ordersStorage;

        public OrderController(ICartsStorage cartsStorage, IOrdersStorage ordersStorage)
        {
            _cartsStorage = cartsStorage;
            _ordersStorage = ordersStorage;
        }

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.IsVisible = false;
            return View();
        }

        [HttpPost]
        public IActionResult Index(OrderViewModel order)
        {
            var userId = Guid.Parse("5c18c843-52c5-455d-b44f-bec0913d047d");
            var cartDb = _cartsStorage.TryGetCardByUserId(userId);

            if (ModelState.IsValid && cartDb != null)
            {
                var oderDb = new Order()
                {
                    Name = order.Name,
                    Address = order.Address,
                    Email = order.Email,
                    Phone = order.Phone,
                    Items = cartDb.Items.Select(item => new OrderItem()
                    {
                        ProductId = item.Product.Id,
                        OrderId = order.Id,
                        Amount = item.Amount,
                    })
                    .ToList(),
                };

                _ordersStorage.Add(oderDb);
                _cartsStorage.Remove(cartDb);

                ViewBag.IsVisible = true;
                return RedirectToAction("Success");
            }

            ViewBag.IsVisible = false;
            return View(order);
        }

        public IActionResult Success()
        {
            return View();
        }
    }
}

shop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db.Services;
using OnlineShopWebApp.Models;

namespace OnlineShopWebApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductsStorage _productsStorage;

        public ProductController(IProductsStorage productsStorage)
        {
            _productsStorage = productsStorage;
        }

        public IActionResult Index(Guid id)
        {
            var productDb = _productsStorage.TryGetById(id);
            var product = new ProductViewModel
            {
                Id = productDb.Id,
                Name = productDb.Name,
                Price = productDb.Price,
                Description = productDb.Description,
                ImageUrl = productDb.ImageUrl
            };

            return View(product);
        }
    }
}

shop/Areas/Admin/Views/Home/Orders.cshtml
@using OnlineShopWebApp.Models
@using OnlineShopWebApp.Properties
@using OnlineShopWebApp.Properties.Helpers

@model List<OrderViewModel>

<div class="row">
    <nav class="col-3">
        @await Html.PartialAsync("AdminNav")
    </nav>

    <div class="col-9">
        <h2>Список заказов</h2>

        <table class="table">
            <thead>
                <tr>
                    <th>Номер</th>
                    <th>Сумма</th>
                    <th>Статус</th>
                    <th>Email</th>
                    <th>Дата</th>
                    <th>Время</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var order in Model)
                {
                    <tr>
                        <td><a asp-area="Admin" asp-controller="Order" asp-action="Details" asp-route-id="@order.Id">@order.Id</a></td>
                        <td>@order.Cost.ToString("0.00") ₽</td>
                        <td>@OrdersStatusHelper.Statuses[order.Status]</td>
                        <td>@order.Email</td>
                        <td>@order.Date.ToShortDateString()</td>
                        <td>@order.Date.ToShortTimeString()</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

shop/Areas/Admin/Views/Home/Products.cshtml
@using OnlineShopWebApp.Models
@using OnlineShopWebApp.Properties

@model List<ProductViewModel>

<div class="row">
    <nav class="col-3">
        @await Html.PartialAsync("AdminNav")
    </nav>
    <div class="col-9">

        <h2>Список продуктов</h2>
        <a class="btn btn-dark"
           asp-area="Admin"
           asp-controller="Product"
           asp-action="Add">
            Добавить новый продукт
        </a>

        @if (Model.Count == 0)
        {
            <p>Список продуктов пуст</p>
        }
        else
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Название</th>
                        <th>Цена, руб</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var product in Model)
                    {
                        <tr>
                            <td>@product.Id</td>
                            <td>
                                <a asp-area="Admin"
                                   asp-controller="Product"
                                   asp-action="Details"
                                   asp-route-id="@product.Id">
                                    @product.Name
                                </a>
                            </td>
                            <td>@($"{product.Price:0.00}")</td>
                            <td>
                                <a class="btn btn-primary"
                                   asp-area="Admin"
                                   asp-controller="Product"
                                   asp-action="Edit"
                                   asp-route-id="@product.Id">
                                    Редактировать
                                </a>
                            </td>
                            <td>
                                <a class="btn btn-danger"
                                   asp-area="Admin"
                                   asp-controller="Product"
                                   asp-action="Remove"
                                   asp-route-id="@product.Id">
                                    Удалить
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</div>

shop/Areas/Admin/Views/Home/Roles.cshtml
@using OnlineShopWebApp.Models
@using OnlineShopWebApp.Properties

@model List<Role>

<div class="row">
    <nav class="col-3">
        @await Html.PartialAsync("AdminNav")
    </nav>
    <div class="col-4">
        <h2>Список ролей</h2>
        <ul class="d-flex flex-column gap-2 list-unstyled">
            @foreach (var role in Model)
            {
                <li class="d-flex justify-content-between">
                    <span class="fw-bold">@role.Name</span>
                    <a class="btn btn-danger"
                       asp-area="Admin"
                       asp-controller="Role"
                       asp-action="Remove"
                       asp-route-name="@role.Name">
                        Удалить
                    </a>
                </li>
            }
            <a class="btn btn-primary align-self-end mt-2"
               asp-area="Admin"
               asp-controller="Role"
               asp-action="Add">
                Создать
            </a>
        </ul>
    </div>
</div>

shop/Areas/Admin/Views/Home/Users.cshtml
@using OnlineShopWebApp.Models
@using OnlineShopWebApp.Properties

@model List<User>

<div class="row">
    <nav class="col-3">
        @await Html.PartialAsync("AdminNav")
    </nav>
    <div class="col-9">
        <h2>Список пользователей</h2>

        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Логин</th>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var user in Model)
                {
                    <tr>
                        <td>
                            <a asp-area="Admin"
                               asp-controller="User"
                               asp-action="Details"
                               asp-route-id="@user.Id">
                                @user.Id
                            </a>
                        </td>
                        <td>@user.Login</td>
                        <td>@user.Email</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>