shop/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShopWebApp.Models;
using OnlineShopWebApp.Models.Enums;
using OnlineShopWebApp.Services;

namespace OnlineShopWebApp.Controllers
{
    public class AdminController : Controller
    {
        private readonly IProductsStorage _productsStorage;
        private readonly IOrdersStorage _ordersStorage;

        public AdminController(IProductsStorage productsStorage, IOrdersStorage ordersStorage)
        {
            _productsStorage = productsStorage;
            _ordersStorage = ordersStorage;
        }

        public IActionResult Orders()
        {
            var orders = _ordersStorage.GetAll();

            return View(orders);
        }

        [HttpGet]
        public IActionResult OrderDetails(int id)
        {
            var order = _ordersStorage.TryGetById(id);

            return View(order);
        }

        [HttpPost]
        public IActionResult OrderDetails(int id, OrderStatuses status)
        {
            var order = _ordersStorage.TryGetById(id);

            if (order != null)
            {
                order.Status = status;
            }

            return View(order);
        }

        public IActionResult Users()
        {
            return View();
        }

        public IActionResult Roles()
        {
            return View();
        }

        public IActionResult Products()
        {
            var products = _productsStorage.GetAll();

            return View(products);
        }

        public IActionResult ProductDetails(int id)
        {
            var product = _productsStorage.TryGetById(id);

            return View(product);
        }

        [HttpGet]
        public IActionResult EditProduct(int id)
        {
            var product = _productsStorage.TryGetById(id);

            return View(product);
        }

        [HttpPost]
        public IActionResult EditProduct(Product product)
        {
            _productsStorage.Update(product);
            return RedirectToAction("Products");
        }

        [HttpGet]
        public IActionResult AddProduct()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddProduct(Product product)
        {
            if (product.Price == 0)
            {
                ModelState["Price"].Errors.Clear();
                ModelState.AddModelError("Price", "Введите цену");
            }

            if (ModelState.IsValid)
            {
                _productsStorage.Add(product);

                return RedirectToAction("Products");
            }
            
            return View(product);
        }

        public IActionResult DeleteProduct(int id)
        {
            var product = _productsStorage.TryGetById(id);

            if (product != null)
            {
                _productsStorage.Remove(product);
            }

            return RedirectToAction("Products");
        }
    }
}

shop/Controllers/AuthorizationController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShopWebApp.Models;
using OnlineShopWebApp.Services;

namespace OnlineShopWebApp.Controllers
{
    public class AuthorizationController : Controller
    {
        private readonly IUsersStorage _usersStorage;

        public AuthorizationController(IUsersStorage usersStorage)
        {
            _usersStorage = usersStorage;
        }

        [HttpGet]
        public IActionResult SignIn()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignIn(Auth auth)
        {
            var user = _usersStorage.Get(auth);

            if (user == null)
            {
                ModelState.AddModelError("", "Вы ввели неверные данные");
            }

            if (ModelState.IsValid == false)
            {
                return View(auth);
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

shop/Views/Shared/Components/Cart/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db.Services;
using OnlineShopWebApp.Properties.Helpers;
using OnlineShopWebApp.Services;

namespace OnlineShopWebApp.Views.Shared.Components.Cart
{
    public class CartViewComponent : ViewComponent
    {
        private readonly ICartsStorage _cartsStorage;

        public CartViewComponent(ICartsStorage cartsStorage)
        {
            _cartsStorage = cartsStorage;
        }

        public IViewComponentResult Invoke()
        {
            var cartDb = _cartsStorage.TryGetCardByUserId(Guid.NewGuid());
            var cart = cartDb.ToCartViewModel();

            var allItemsAmount = cart?.ItemsAmount;

            return View("Cart", allItemsAmount);
        }
    }
}

shop/Views/Shared/AdminNav.cshtml
<ul class="list-unstyled">
    <li>
        <a class="btn"
           asp-controller="Admin"
           asp-action="Orders">
            Заказы
        </a>
    </li>
    <li>
        <a class="btn"
           asp-controller="Admin"
           asp-action="Users">
            Пользователи
        </a>
    </li>
    <li>
        <a class="btn"
           asp-controller="Admin"
           asp-action="Roles">
            Роли
        </a>
    </li>
    <li>
        <a class="btn"
           asp-controller="Admin"
           asp-action="Products">
            Продукты
        </a>
    </li>
</ul>

shop/Views/Shared/Header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand"
               asp-area=""
               asp-controller="Home"
               asp-action="Index">
                Online Shop
            </a>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark"
                           asp-area=""
                           asp-controller="Home"
                           asp-action="Index">
                            Главная
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark"
                           asp-area=""
                           asp-controller="Authorization"
                           asp-action="SignIn">
                            Войти
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark"
                           asp-area=""
                           asp-controller="Cart"
                           asp-action="Index">
                            Корзина @await Component.InvokeAsync("Cart")
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark"
                           asp-area="Admin"
                           asp-controller="Home"
                           asp-action="Orders">
                            Администратор
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/shop.styles.css" asp-append-version="true" />
</head>
<body>
    @await Html.PartialAsync("Header");

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @await Html.PartialAsync("_ValidationScriptsPartial")

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>